apiVersion: v1
kind: Secret
metadata:
  name: popcon-secret
  namespace: popcon
type: Opaque
data:
  # echo -n "값" | base64 로 인코딩된 값
  DB_USERNAME: cG9wY29uX3VzZXI=       # popcon_user
  DB_PASSWORD: cG9wY29uMTIzNCE=       # popcon1234!
  DB_ROOT_PASSWORD: cm9vdDEyMzQh      # root1234!
  DB_NAME: cG9wY29u                   # popcon